# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x05user1\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xa7\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.user1.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.user1.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.user1.User\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.user1.User\".\n\x11UpdateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.user1.User\"/\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.user1.User\"/\n\x12\x44\x65leteUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.user1.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x91\x03\n\x05User1\x12\x32\n\x08SayHello\x12\x13.user1.HelloRequest\x1a\x11.user1.HelloReply\x12=\n\x08GetUsers\x12\x16.user1.GetUsersRequest\x1a\x17.user1.GetUsersResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.user1.GetUserByIdRequest\x1a\x1a.user1.GetUserByIdResponse\"\x00\x12\x43\n\nCreateUser\x12\x18.user1.CreateUserRequest\x1a\x19.user1.CreateUserResponse\"\x00\x12\x43\n\nUpdateUser\x12\x18.user1.UpdateUserRequest\x1a\x19.user1.UpdateUserResponse\"\x00\x12\x43\n\nDeleteUser\x12\x18.user1.DeleteUserRequest\x1a\x19.user1.DeleteUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=21
  _globals['_HELLOREQUEST']._serialized_end=49
  _globals['_HELLOREPLY']._serialized_start=51
  _globals['_HELLOREPLY']._serialized_end=80
  _globals['_USER']._serialized_start=83
  _globals['_USER']._serialized_end=250
  _globals['_GETUSERSREQUEST']._serialized_start=252
  _globals['_GETUSERSREQUEST']._serialized_end=269
  _globals['_GETUSERSRESPONSE']._serialized_start=271
  _globals['_GETUSERSRESPONSE']._serialized_end=317
  _globals['_GETUSERBYIDREQUEST']._serialized_start=319
  _globals['_GETUSERBYIDREQUEST']._serialized_end=351
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=353
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=401
  _globals['_CREATEUSERREQUEST']._serialized_start=403
  _globals['_CREATEUSERREQUEST']._serialized_end=449
  _globals['_CREATEUSERRESPONSE']._serialized_start=451
  _globals['_CREATEUSERRESPONSE']._serialized_end=498
  _globals['_UPDATEUSERREQUEST']._serialized_start=500
  _globals['_UPDATEUSERREQUEST']._serialized_end=546
  _globals['_UPDATEUSERRESPONSE']._serialized_start=548
  _globals['_UPDATEUSERRESPONSE']._serialized_end=595
  _globals['_DELETEUSERRESPONSE']._serialized_start=597
  _globals['_DELETEUSERRESPONSE']._serialized_end=644
  _globals['_DELETEUSERREQUEST']._serialized_start=646
  _globals['_DELETEUSERREQUEST']._serialized_end=677
  _globals['_USER1']._serialized_start=680
  _globals['_USER1']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
