# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07greeter\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xa7\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\"\x11\n\x0fGetUsersRequest\"0\n\x10GetUsersResponse\x12\x1c\n\x05users\x18\x01 \x03(\x0b\x32\r.greeter.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x13GetUserByIdResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.greeter.User\"0\n\x11\x43reateUserRequest\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.greeter.User\"1\n\x12\x43reateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.greeter.User\"0\n\x11UpdateUserRequest\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.greeter.User\"1\n\x12UpdateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.greeter.User\"1\n\x12\x44\x65leteUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.greeter.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xab\x03\n\x07Greeter\x12\x36\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\x12\x41\n\x08GetUsers\x12\x18.greeter.GetUsersRequest\x1a\x19.greeter.GetUsersResponse\"\x00\x12J\n\x0bGetUserById\x12\x1b.greeter.GetUserByIdRequest\x1a\x1c.greeter.GetUserByIdResponse\"\x00\x12G\n\nCreateUser\x12\x1a.greeter.CreateUserRequest\x1a\x1b.greeter.CreateUserResponse\"\x00\x12G\n\nUpdateUser\x12\x1a.greeter.UpdateUserRequest\x1a\x1b.greeter.UpdateUserResponse\"\x00\x12G\n\nDeleteUser\x12\x1a.greeter.DeleteUserRequest\x1a\x1b.greeter.DeleteUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=23
  _globals['_HELLOREQUEST']._serialized_end=51
  _globals['_HELLOREPLY']._serialized_start=53
  _globals['_HELLOREPLY']._serialized_end=82
  _globals['_USER']._serialized_start=85
  _globals['_USER']._serialized_end=252
  _globals['_GETUSERSREQUEST']._serialized_start=254
  _globals['_GETUSERSREQUEST']._serialized_end=271
  _globals['_GETUSERSRESPONSE']._serialized_start=273
  _globals['_GETUSERSRESPONSE']._serialized_end=321
  _globals['_GETUSERBYIDREQUEST']._serialized_start=323
  _globals['_GETUSERBYIDREQUEST']._serialized_end=355
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=357
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=407
  _globals['_CREATEUSERREQUEST']._serialized_start=409
  _globals['_CREATEUSERREQUEST']._serialized_end=457
  _globals['_CREATEUSERRESPONSE']._serialized_start=459
  _globals['_CREATEUSERRESPONSE']._serialized_end=508
  _globals['_UPDATEUSERREQUEST']._serialized_start=510
  _globals['_UPDATEUSERREQUEST']._serialized_end=558
  _globals['_UPDATEUSERRESPONSE']._serialized_start=560
  _globals['_UPDATEUSERRESPONSE']._serialized_end=609
  _globals['_DELETEUSERRESPONSE']._serialized_start=611
  _globals['_DELETEUSERRESPONSE']._serialized_end=660
  _globals['_DELETEUSERREQUEST']._serialized_start=662
  _globals['_DELETEUSERREQUEST']._serialized_end=693
  _globals['_GREETER']._serialized_start=696
  _globals['_GREETER']._serialized_end=1123
# @@protoc_insertion_point(module_scope)
